added patch cc missed parts
Selina-Finance/ms-lending-api pull request #100
Opened 2022-11-29 16:05 UTC by Vadym-Lopatka

[LA-200]

[LA-200]: https://selina.atlassian.net/browse/LA-200?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2022-11-29 16:37 UTC, bpoon-selina requested changes

2022-11-30 09:03 UTC, Vadym-Lopatka commented on src/test/java/com/selina/lending/internal/service/creaditCommitments/UpdateCreditCommitmentsServiceImplTest.java
> +import com.selina.lending.internal.dto.creaditCommitments.CreditCommitmentResponse;
it would be resolved when we check all together on an integration stage.
For now, it looks like that API returns ApplicationResponse.

2022-11-30 09:04 UTC, Vadym-Lopatka commented on src/main/java/com/selina/lending/internal/api/CreditCommitmentsApi.java
> +import com.selina.lending.internal.dto.creaditCommitments.CreditCommitmentResponse;
the typo will be fixed

2022-11-30 10:50 UTC, Vadym-Lopatka commented
/hold

2022-11-30 13:45 UTC, Vadym-Lopatka commented
/hold cancel

2022-11-30 13:52 UTC, bpoon-selina commented
/approve

2022-11-30 13:54 UTC, merged