GRO-1561 HTTP client for creating Quick Quote with Credit Commitments applications
Selina-Finance/ms-lending-api pull request #150
Opened 2023-03-27 13:47 UTC by KastorDriver

[GRO-1561](https://selina.atlassian.net/browse/GRO-1561)
An HTTP client for a new service for creating Quick Quote with Credit Commitment applications

[GRO-1561]: https://selina.atlassian.net/browse/GRO-1561?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-03-27 15:56 UTC, bpoon-selina requested changes

2023-03-27 15:56 UTC, bpoon-selina commented on src/main/java/com/selina/lending/internal/service/application/domain/quotecc/request/Address.java
> +package com.selina.lending.internal.service.application.domain.quotecc.request;
We do have an Address object already in  com.selina.lending.internal.service.application.domain
I think we can use that rather then create a new object?

2023-03-27 15:56 UTC, bpoon-selina commented on src/main/java/com/selina/lending/internal/service/application/domain/quotecc/request/Applicant.java
> +package com.selina.lending.internal.service.application.domain.quotecc.request;
Same here, we have an Applicant in  com.selina.lending.internal.service.application.domain which is something I think we should reuse - and only send through the fields we have?

2023-03-27 15:56 UTC, bpoon-selina commented on src/main/java/com/selina/lending/internal/service/application/domain/quotecc/request/Employment.java
> +package com.selina.lending.internal.service.application.domain.quotecc.request;
Same here, we have Employment in  com.selina.lending.internal.service.application.domain

2023-03-27 15:56 UTC, bpoon-selina commented on src/main/java/com/selina/lending/internal/service/application/domain/quotecc/request/Income.java
> +package com.selina.lending.internal.service.application.domain.quotecc.request;
We already have  Income in com.selina.lending.internal.service.application.domain

2023-03-27 15:56 UTC, bpoon-selina commented on src/main/java/com/selina/lending/internal/service/application/domain/quotecc/request/LoanInformation.java
> +public class LoanInformation {
We already have LoanInformation in  com.selina.lending.internal.service.application.domain. We can reuse these.

2023-03-27 15:56 UTC, bpoon-selina commented on src/main/java/com/selina/lending/internal/service/application/domain/quotecc/request/PriorCharges.java
> +public class PriorCharges {
We already have PriorCharges in  com.selina.lending.internal.service.application.domain

2023-03-27 15:56 UTC, bpoon-selina commented on src/main/java/com/selina/lending/internal/service/application/domain/quotecc/request/QuickQuoteCCRequest.java
> +public class QuickQuoteCCRequest {
In order to send a request and receive the response from MW, we will need a mapper class.  But since the quote_broker api is not ready yet, its probably not possible to add this yet

2023-03-27 16:33 UTC, KastorDriver commented on src/main/java/com/selina/lending/internal/service/application/domain/quotecc/request/QuickQuoteCCRequest.java
> +public class QuickQuoteCCRequest {
Sure! I will add mappers in the scope of the [GRO-1563](https://selina.atlassian.net/browse/GRO-1563)

2023-03-28 07:43 UTC, bpoon-selina commented
/approve

2023-03-28 07:44 UTC, merged