GRO-1826 send middleware create application event for QQ applications
Selina-Finance/ms-lending-api pull request #171
Opened 2023-04-20 18:17 UTC by KastorDriver

#### Description
[GRO-1826](https://selina.atlassian.net/browse/GRO-1826)

#### Background Context

#### Additional Information
![image](https://user-images.githubusercontent.com/19750652/233452988-2151fc58-3398-4ad4-97e4-945dec55c2cc.png)

2023-04-20 18:55 UTC, KastorDriver commented
/hold

2023-04-21 08:59 UTC, WeiLu1 commented on src/main/java/com/selina/lending/internal/mapper/AddressMapper.java
> +import org.mapstruct.MappingConstants;
unused import, can delete

2023-04-21 09:00 UTC, WeiLu1 commented on src/main/java/com/selina/lending/internal/mapper/EmploymentMapper.java
> +import org.mapstruct.MappingConstants;
unused import, can delete

2023-04-21 09:00 UTC, WeiLu1 commented on src/main/java/com/selina/lending/internal/mapper/IncomeItemMapper.java
> +import org.mapstruct.MappingConstants;
unused import, can delete

2023-04-21 09:01 UTC, WeiLu1 commented on src/main/java/com/selina/lending/internal/mapper/QuickQuoteApplicantMapper.java
> +import org.mapstruct.MappingConstants;
unused import, can delete

2023-04-21 09:16 UTC, bpoon-selina requested changes

2023-04-21 09:16 UTC, bpoon-selina commented on src/main/java/com/selina/lending/messaging/mapper/middleware/AddressMapper.java
> +public interface AddressMapper {
Is there a reason you need to create a new mapper for Address? Are you not able to use the existing mapper which is doing the exact same thing?

2023-04-21 09:16 UTC, bpoon-selina commented on src/main/java/com/selina/lending/messaging/mapper/middleware/IncomeItemMapper.java
> +public interface IncomeItemMapper {
Same for this mapper. Can we use existing mapper?

2023-04-21 09:16 UTC, bpoon-selina commented on src/main/java/com/selina/lending/messaging/mapper/middleware/IncomeMapper.java
> +public interface IncomeMapper {
And same for this mapper?

2023-04-21 09:22 UTC, WeiLu1 commented on src/main/java/com/selina/lending/messaging/publisher/MiddlewareCreateApplicationEventPublisher.java
> +            kafkaTemplate.send(topic, event).get().getRecordMetadata();
Do we need to add callbacks on whether or not the event send was successful or failed? 
Because the `.send` method returns a listenableFuture which does not throw an error in itself.
Does the `.get` method chained after `.send` account for this and can throw errors correctly?

2023-04-21 09:24 UTC, WeiLu1 commented on src/test/java/com/selina/lending/config/IntegrationTestConfig.java
> +import org.mockito.Mockito;
unused import, can delete

2023-04-21 09:26 UTC, WeiLu1 commented on src/test/java/com/selina/lending/messaging/mapper/brokerrequest/BrokerRequestEventMapperTest.java
> +import com.selina.lending.messaging.mapper.brokerrequest.BrokerRequestEventMapper;
unused import, can delete

2023-04-21 09:26 UTC, bpoon-selina requested changes

2023-04-21 09:26 UTC, bpoon-selina commented on src/main/java/com/selina/lending/api/controller/QuickQuoteController.java
>  public class QuickQuoteController implements QuickQuoteOperations {
For the QQ endpoint - once the application has been saved by MW, have you checked to see if the application can be retrieved by a GET?

2023-04-21 09:26 UTC, WeiLu1 commented on src/test/java/com/selina/lending/messaging/mapper/middleware/MiddlewareCreateApplicationEventMapperTest.java
> +import com.selina.lending.messaging.publisher.MiddlewareCreateApplicationEventPublisher;
unused imports, can delete

2023-04-21 09:26 UTC, WeiLu1 commented on src/test/java/com/selina/lending/messaging/mapper/middleware/MiddlewareCreateApplicationEventMapperTest.java
> +import org.springframework.boot.test.context.SpringBootTest;
unused import, can delete

2023-04-21 09:28 UTC, WeiLu1 commented on src/test/java/com/selina/lending/messaging/mapper/middleware/MiddlewareCreateApplicationEventMapperTest.java
> +    private void assertApplicants(List<Applicant> applicants) {
how come these methods and the ones below are not annotated with `@Test`?

2023-04-21 09:28 UTC, bpoon-selina requested changes

2023-04-21 09:28 UTC, bpoon-selina commented on src/main/java/com/selina/lending/messaging/mapper/middleware/QuickQuoteApplicantMapper.java
> +public interface QuickQuoteApplicantMapper {
Same for this mapper

2023-04-21 09:37 UTC, bpoon-selina requested changes

2023-04-21 09:37 UTC, bpoon-selina commented on src/test/java/com/selina/lending/messaging/mapper/middleware/MiddlewareCreateApplicationEventMapperTest.java
> +        assertThat(firstAddress.getBuildingNumber(), equalTo(BUILDING_NUMBER));
duplicated assertion

2023-04-21 11:13 UTC, DanielFernandesPTech commented on src/main/java/com/selina/lending/messaging/mapper/middleware/IncomeItemMapper.java
> +@Mapper(componentModel = MappingConstants.ComponentModel.SPRING,
Why you use this approach instead of `INSTANCE` approach?

2023-04-21 11:57 UTC, KastorDriver commented on src/main/java/com/selina/lending/internal/mapper/AddressMapper.java
> +import org.mapstruct.MappingConstants;
Good catch!
I've deleted all unused imports.
Thanks!

2023-04-21 11:58 UTC, KastorDriver commented on src/test/java/com/selina/lending/messaging/mapper/middleware/MiddlewareCreateApplicationEventMapperTest.java
> +        assertThat(firstAddress.getBuildingNumber(), equalTo(BUILDING_NUMBER));
Deleted

2023-04-21 12:18 UTC, KastorDriver commented on src/main/java/com/selina/lending/internal/service/FilterApplicationServiceImpl.java
> +        return decisionResponse;
The reason for that order is we need first to get a response from the ms-selection with offers and only then "ask" MW to create it.

In case we got some error from the ms-selection service (or the Decisioning service) we can't be sure the MW will be able to create the same application.

This is why, in my personal opinion, the order matters and to check that order I use Mockito.InOrder functionality in the [test](https://github.com/Selina-Finance/ms-lending-api/pull/171/files#diff-324ef744c15ce9b73f29bce3c2cc5c0a147848bc49c62da4289010d19c69cac8R70)

2023-04-21 13:06 UTC, KastorDriver commented on src/main/java/com/selina/lending/messaging/mapper/middleware/AddressMapper.java
> +public interface AddressMapper {
Good question!
As you can see these mappers aren't just interfaces with static methods, they are real Spring Beans because of the 
componentModel = MappingConstants.ComponentModel.SPRING

That means I can inject into them another Spring Beans.
I needed that in the MiddlewareCreateApplicationEventMapper where I can now inject a TokenService and [enrich a request with a "sourceAccount"](https://github.com/Selina-Finance/ms-lending-api/pull/171/files#diff-ab98e9b7c0f61d2a9d5b73a8790a2d400ed09e2648751cb2161813da2ca2a8c9R28) value without writing an additional "enricher". Isn't that cool? :)

Unfortunately, if that mapper uses other mappers, all of them should be defined as Spring Beans as well. So, I got two options here:
1. Turn every other mapper into Spring Beans and be able to reuse them. And I did, but that led to many changes in source code and unit tests, so I reverted these changes and decided to go by the second path
2. Create from scratch all mappers the MiddlewareCreateApplicationEventMapper needs to use despite the fact they are identical to the ones which we already have.

One day I will turn all our mappers into Spring Beans, so I will be able to reuse them instead of newly created ones.

BTW, [mapstruct documentation says](https://mapstruct.org/documentation/stable/reference/html/#using-dependency-injection) it's the most preferable way to define mappers as Spring Beans :)
![image](https://user-images.githubusercontent.com/19750652/233643457-c68b21c7-0b16-44b6-9d17-12886c824dec.png)

2023-04-21 13:09 UTC, KastorDriver commented on src/main/java/com/selina/lending/messaging/mapper/middleware/IncomeItemMapper.java
> +public interface IncomeItemMapper {
Please check my previous [response](https://github.com/Selina-Finance/ms-lending-api/pull/171#discussion_r1173746090)

2023-04-21 13:09 UTC, KastorDriver commented on src/main/java/com/selina/lending/messaging/mapper/middleware/IncomeMapper.java
> +public interface IncomeMapper {
Please check my previous [response](https://github.com/Selina-Finance/ms-lending-api/pull/171#discussion_r1173746090)

2023-04-21 13:11 UTC, KastorDriver commented on src/main/java/com/selina/lending/messaging/mapper/middleware/QuickQuoteApplicantMapper.java
> +public interface QuickQuoteApplicantMapper {
Please check my previous [response](https://github.com/Selina-Finance/ms-lending-api/pull/171#discussion_r1173746090)

2023-04-21 13:11 UTC, KastorDriver commented on src/main/java/com/selina/lending/messaging/mapper/middleware/IncomeItemMapper.java
> +@Mapper(componentModel = MappingConstants.ComponentModel.SPRING,
Please check my previous [response](https://github.com/Selina-Finance/ms-lending-api/pull/171#discussion_r1173746090)

2023-04-21 13:23 UTC, bpoon-selina commented on src/main/java/com/selina/lending/messaging/mapper/middleware/AddressMapper.java
> +public interface AddressMapper {
Thank you for the explanation! Yes i saw the injection of the TokenService- super cool indeed!!

2023-04-21 13:25 UTC, KastorDriver commented on src/test/java/com/selina/lending/messaging/mapper/middleware/MiddlewareCreateApplicationEventMapperTest.java
> +    private void assertApplicants(List<Applicant> applicants) {
All of these methods are not tests themselves. We use them as helper methods to test some particular mappings, so the main test is not bloated and easy to read.
![image](https://user-images.githubusercontent.com/19750652/233646891-dca03f17-0f62-4111-b6b9-e65032556b5c.png)

2023-04-21 13:42 UTC, DanielFernandesPTech commented on src/main/java/com/selina/lending/messaging/mapper/middleware/IncomeItemMapper.java
> +@Mapper(componentModel = MappingConstants.ComponentModel.SPRING,
Nice Roman :smile:

2023-04-21 13:52 UTC, KastorDriver commented on src/main/java/com/selina/lending/api/controller/QuickQuoteController.java
>  public class QuickQuoteController implements QuickQuoteOperations {
Not yet because the [PR-248](https://github.com/Selina-Finance/ms-middleware-api/pull/248) for MW Kafka listener is still open [MW-181](https://selina.atlassian.net/browse/MW-181)

In my personal opinion, what we need to check in the scope of this ticket is that the Lending API sends a Kafka event to a broker in a proper format.
![image](https://user-images.githubusercontent.com/19750652/233653694-2473b77b-47cb-4e56-beb8-4aa09693efa2.png)

2023-04-21 14:07 UTC, KastorDriver commented on src/main/java/com/selina/lending/messaging/publisher/MiddlewareCreateApplicationEventPublisher.java
> +            kafkaTemplate.send(topic, event).get().getRecordMetadata();
You are right!
So, the ListenableFuture extends the Future
`public interface ListenableFuture<T> extends Future<T> {`

where we have the get() method with the next Java doc
![image](https://user-images.githubusercontent.com/19750652/233656678-5ff98baa-7386-4782-a4ba-8cc001e2b9f7.png)

This way the publisher will wait until a message is sent or throw an ExecutionException in case something went wrong that will be matched and processed in the `publish `method

2023-04-21 14:17 UTC, bpoon-selina commented
/lgtm

2023-04-21 14:26 UTC, KastorDriver commented
/hold cancel

2023-04-21 14:27 UTC, merged